services:
  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: decapapeus-web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: decapapeus-nginx
    ports:
      - "8080:80"  # Puerto externo 8080 → puerto interno 80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d  # Configuración Nginx personalizada
    depends_on:
      - web
    restart: unless-stopped

  jsonserver:
    image: node:20-alpine
    container_name: jsonserver
    working_dir: /app
    command: sh -c "npm i -g json-server && json-server --watch /data/products.json --host 0.0.0.0 --port 3000"
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
    restart: unless-stopped

#services:
#  web:
#    build:
#      context: .
#      dockerfile: .docker/Dockerfile
#    container_name: decapapeus-web
#    ports:
#      - "80:80"
#    volumes:
#      - ./:/var/www
#    restart: unless-stopped
#   db:
#     image: mysql:8.0
#     ports:
#       - "3306:3306"
#     command: --default-authentication-plugin=mysql_native_password
#     environment:
#       MYSQL_DATABASE: pruebadb
#       MYSQL_USER: usuario
#       MYSQL_PASSWORD: 1234
#       MYSQL_ROOT_PASSWORD: 1234
#     volumes:
#       - persistent:/var/lib/mysql
#     networks:
#       - default
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     links:
#       - db:db
#     ports:
#       - 8000:80
#     environment:
#       MYSQL_USER: usuario
#       MYSQL_PASSWORD: 1234
#       MYSQL_ROOT_PASSWORD: 1234
# volumes:
#   persistent:

#     null
